# This docker image is meant for the analysis of high dimensionality flow data with CONDOR

# I start from the Bioconductor 3.17 image with RStudio Server
FROM bioconductor/bioconductor_docker:RELEASE_3_17

# installing necessary packages (CRAN + Bioconductor)
RUN Rscript -e 'BiocManager::install(update = T, ask = F, version = "3.17")' && \
    Rscript -e 'BiocManager::install(c("flowCore", "devtools", "Rtsne", "umap", "ggplot2", "ggpubr",  \
                                       "vegan", "diffusionMap", "FlowSOM", "gplots", "grid", "gridExtra", \
                                       "reshape2", "RColorBrewer", "scatterplot3d", "rgl", "Biobase", "Rmisc", \
                                       "tidyverse", "pheatmap", "viridis", "rainbow", "destiny", \
                                       "SingleCellExperiment", "slingshot", "ggrastr", \
                                       "uwot", "FlowSOM", "caret", "factoextra", "harmony", "flowWorkspace", \
                                       "CytoML", "Biobase", "Hmisc", "CytoDx", "DelayedMatrixStats"), version = "3.17")'

RUN Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/randomForest_4.7-1.1.tar.gz", repos=NULL, type="source")'

# install github packages
RUN Rscript -e 'devtools::install_github("JinmiaoChenLab/Rphenograph")' && \
    Rscript -e 'devtools::install_github("stuchly/Rphenoannoy")'

# install CONDOR
COPY condor_0.1.4.tar.gz /tmp/condor_0.1.4.tar.gz
RUN Rscript -e 'install.packages("/tmp/condor_0.1.4.tar.gz", repos = NULL, type = "source")'

# example to run this docker image
# docker run -dp 8787:8787 -e USER=mariorossi -e PASSWORD=mariorossi --name fc_analysis -v /mnt/e/docker_test:/home/lorenzo/data/ lorenzobonaguro/condor:v014