# This docker image is meant for the analysis of high dimensionality flow data with CONDOR

# I start from the Bioconductor 3.17 image with RStudio Server
FROM bioconductor/bioconductor_docker:RELEASE_3_20

# Install miniconda
ENV CONDA_DIR=/opt/conda
RUN wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" -O ~/miniforge.sh && \
    /bin/bash ~/miniforge.sh -b -p /opt/conda

RUN rm /root/miniforge.sh

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# Add the conda repositories

RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda
RUN conda config --set channel_priority strict

# Prepare the enviroment for Astir

RUN conda create --name astir python=3.6

## Install astir in this conda
RUN cd /opt && git clone https://github.com/camlab-bioml/astir.git && cd astir && conda run -n astir pip install .

RUN rm -r /opt/astir

# Install geosketch in the default 
RUN pip install geosketch

# Update Bioconductor and install devtools
RUN Rscript -e 'BiocManager::install(update = T, ask = F, version = "3.20")'

RUN Rscript -e 'BiocManager::install("devtools",version = "3.20")'

# install CONDOR
RUN Rscript -e 'devtools::install_github("lorenzobonaguro/cyCONDOR@dev", build_vignettes = FALSE, repos = BiocManager::repositories())'

# example to run this docker image
# docker run -dp 8787:8787 -e PASSWORD=mariorossi --name fc_analysis -v /mnt/e/docker_test:/home/lorenzo/data/ lorenzobonaguro/cycondor:v030